grafikart_db:
  image: mariadb
  # restart: always
  ports:
    - "3307:3306"
  env_file:
    - .env
  environment:
    MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE_GRAFIKART}
  volumes: 
    - ./build/mariadb/grafikart:/docker-entrypoint-initdb.d
    - ./mysql/grafikart:/var/lib/mysql
    
lior_db:
  image: mariadb
  # restart: always
  ports:
    - "3308:3306"
  env_file:
    - .env
  environment:
    MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE_LIOR}
  volumes: 
    - ./build/mariadb/lior:/docker-entrypoint-initdb.d
    - ./mysql/lior:/var/lib/mysql
