# docker-compose.override.yml
version: "3.7"
services:
  mariadb:
    volumes:
      - "./docker/mariadb/grafikart:/docker-entrypoint-initdb.d"
      - "./mysql/grafikart:/var/lib/mysql"
    ports:
      # - "3307:3306"
      - "${MARIADB_PORT_GRAFIKART}:3306"

  # php:
  #   volumes:
  #     - "./symfony/grafikart/:/usr/src/app"

  # nginx:
  #   volumes:
  #     - "./symfony/grafikart/public/:/usr/src/app"
  #     - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
  #   ports:
  #     - "${NGINX_PORT_GRAFIKART}:80"
  # adminer:
  #   ports:
  #     - "${ADMINER_PORT}:8080"
