# docker-compose.override.yml
version: "3.7"
services:
  mariadb:
    volumes:
      - "./docker/mariadb/lior:/docker-entrypoint-initdb.d"
      - "./mysql/lior:/var/lib/mysql"
    ports:
      - "3307:3306"

  php:
    volumes:
      - "./symfony/lior/:/usr/src/app"

  nginx:
    volumes:
      - "./symfony/lior/public/:/usr/src/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "${NGINX_PORT_LIOR}:80"
  # adminer:
  #   ports:
  #     - "${ADMINER_PORT}:8080"
